application: your-app-id
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /home/static
  static_dir: static

- url: /home
  static_files: ./templates/index.html
  upload: ./templates/index.html
 
- url: /home/user_home.*
  script: main.application
  login: required
  auth_fail_action: redirect


libraries:
- name: django
  version: "1.4"
